TDDNS_SERVER_URL=https://ns1.1stcall.uk
TDDNS_API_TOKEN=74ff20649e778a1c5bc9baf7b2b13e1e235865151096d935cb104f6f04b9b1ad
TDDNS_DOMAIN=rpicm4-1.1stcall.uk
TDDNS_ZONE=
TDDNS_VERBOSE=false
TDDNS_CHECK_ONLY=false
TDDNS_TTL=100
TDDNS_UPDATE_PTR=true
